version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: recycle-metrics-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recycle-metrics
    ports:
      - "5432:5432"
    volumes:
      - recyclemetrics-data:/var/lib/postgresql/data

volumes:
  recyclemetrics-data:
